-- MySQL Script generated by MySQL Workbench
-- Fri Sep 21 16:36:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL,
  `nom_tipo_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nom_usuario` VARCHAR(45) NULL,
  `contra_usuario` VARCHAR(45) NULL,
  `url_foto_usuario` VARCHAR(45) NULL,
  `tipo_usuario_id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo_inve_semillero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grupo_inve_semillero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grupo_inve_semillero` (
  `id_grupo` INT NOT NULL,
  `nom_grupo` VARCHAR(45) NULL,
  `sigla_signif_grupo` VARCHAR(45) NULL,
  `objetivo_grupo` VARCHAR(45) NULL,
  `programa_grupo` VARCHAR(45) NULL,
  `url_logo_grupo` VARCHAR(45) NULL,
  `mision_grupo` VARCHAR(45) NULL,
  `vision_grupo` VARCHAR(45) NULL,
  `justif_grupo` VARCHAR(45) NULL,
  `quien_somos_grupo` VARCHAR(45) NULL,
  `grupo_inve_semillero_id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`integrante_has_grupo_inve_semillero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`integrante_has_grupo_inve_semillero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`integrante_has_grupo_inve_semillero` (
  `usuario_id_usuario` INT NOT NULL,
  `grupo_inve_semillero_id_grupo` INT NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `grupo_inve_semillero_id_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `id_proyecto` INT NOT NULL,
  `nom_proyecto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto_has_grupo_inve_semillero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proyecto_has_grupo_inve_semillero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proyecto_has_grupo_inve_semillero` (
  `proyecto_id_proyecto` INT NOT NULL,
  `grupo_inve_semillero_id_grupo` INT NOT NULL,
  PRIMARY KEY (`proyecto_id_proyecto`, `grupo_inve_semillero_id_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario_has_proyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario_has_proyecto` (
  `usuario_id_usuario` INT NOT NULL,
  `proyecto_id_proyecto` INT NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `proyecto_id_proyecto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
